name: Deploy

on:
  pull-request:
    tags:
      - 'backend-v*'
      - 'frontend-v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        run: |
          SERVICE=$(echo ${{ github.ref }} | cut -d'-' -f1)
          VERSION=$(echo ${{ github.ref }} | cut -d'-' -f2)
          echo "service=$SERVICE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./apps/${{ steps.meta.outputs.service }}
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ steps.meta.outputs.service }}:${{ steps.meta.outputs.version }}
            ${{ secrets.REGISTRY_URL }}/${{ steps.meta.outputs.service }}:latest

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          ./scripts/helm/deploy.sh \
            ${{ github.event.deployment.environment }} \
            ${{ steps.meta.outputs.service }} \
            ${{ steps.meta.outputs.version }}
